#' Operations performance from data frame generated by readCMCreport.R
#'
#' \code{performanceCMCreport} returns a print lines with statistic data and
#' plot key indicators.
#'
#' @author Mario Pisa
#' @param data.frame generated by readCMCreport.R
#' @return screen print lines
#' @examples
#' performanceCMCreport(operations)
#' performanceCMCreport(readCMCreport("../myCMCreports/Historico20160909.csv"))
#' @seealso \url{https://www.cmcmarkets.com/}
# Calculate operation's basic statistic
performanceCMCreport <- function(df) {
   agrupar <- function(opes) {
      P3 <- vector('numeric'); pP3 <- vector('numeric')
      P2 <- vector('numeric'); pP2 <- vector('numeric')
      P1 <- vector('numeric'); pP1 <- vector('numeric')
      P0 <- vector('numeric'); pP0 <- vector('numeric')
      G0 <- vector('numeric'); pG0 <- vector('numeric')
      G1 <- vector('numeric'); pG1 <- vector('numeric')
      G2 <- vector('numeric'); pG2 <- vector('numeric')
      G3 <- vector('numeric'); pG3 <- vector('numeric')
      j <- 1; k <- 1; l <- 1; m <- 1
      n <- 1; o <- 1; p <- 1; q <- 1
      for (i in 1:nrow(opes)) {
         if (opes$WLEUR[i] <= -3) {
            P3[j] <- opes$WLEUR[i]
            j <- j + 1
         }else if (opes$WLEUR[i] <= -2) {
            P2[k] <- opes$WLEUR[i]
            k <- k + 1
         }else if (opes$WLEUR[i] <= -1) {
            P1[l] <- opes$WLEUR[i]
            l <- l + 1
         }else if (opes$WLEUR[i] <= 0) {
            P0[m] <- opes$WLEUR[i]
            m <- m + 1
         }else if (opes$WLEUR[i] > 0 & opes$WLEUR[i] < 1) {
            G0[n] <- opes$WLEUR[i]
            n <- n + 1
         }else if (opes$WLEUR[i] >= 1 & opes$WLEUR[i] < 2) {
            G1[o] <- opes$WLEUR[i]
            o <- o + 1
         }else if (opes$WLEUR[i] >= 2 & opes$WLEUR[i] < 3) {
            G2[p] <- opes$WLEUR[i]
            p <- p + 1
         }else if (opes$WLEUR[i] >= 3) {
            G3[q] <- opes$WLEUR[i]
            q <- q + 1
         }
      }
      pP3 <- round(length(P3) / (nrow(opes) - (length(G0) + length(P0))), digits = 2); lP3 <- list(P3 = P3, pP3 = pP3)
      pP2 <- round(length(P2) / (nrow(opes) - (length(G0) + length(P0))), digits = 2); lP2 <- list(P2 = P2, pP2 = pP2)
      pP1 <- round(length(P1) / (nrow(opes) - (length(G0) + length(P0))), digits = 2); lP1 <- list(P1 = P1, pP1 = pP1)
      pP0 <- round(length(P0) / (nrow(opes) - (length(G0) + length(P0))), digits = 2); lP0 <- list(P0 = P0, pP0 = pP0)
      pG0 <- round(length(G0) / (nrow(opes) - (length(G0) + length(G0))), digits = 2); lG0 <- list(G0 = G0, pG0 = pG0)
      pG1 <- round(length(G1) / (nrow(opes) - (length(G0) + length(G0))), digits = 2); lG1 <- list(G1 = G1, pG1 = pG1)
      pG2 <- round(length(G2) / (nrow(opes) - (length(G0) + length(G0))), digits = 2); lG2 <- list(G2 = G2, pG2 = pG2)
      pG3 <- round(length(G3) / (nrow(opes) - (length(G0) + length(G0))), digits = 2); lG3 <- list(G3 = G3, pG3 = pG3)
      grupos <- list(P3 = lP3, P2 = lP2, P1 = lP1, P0 = lP0, G0 = lG0, G1 = lG1, G2 = lG2, G3 = lG3)
      grupos
   }
   print("Summary for Wins and Losses")
   print(summary(df$WLEUR))
   print("Summary for Wins")
   wins <- df$WLEUR[which(df$WLEUR > 0)]
   print(summary(wins))
   print("Summary for Losses")
   losses <- df$WLEUR[which(df$WLEUR <= 0)]
   print(summary(losses))
   print("Summary for Saldo")
   print(summary(df$Saldo))
   print("Summary for R")
   print(summary(df$brratio))
   print(paste("Número de operaciones: ", nrow(df)))
   print(paste("Ganadoras: ", length(wins), round((length(wins)/nrow(df))*100, digits = 2), "%", "Perdedoras: ", length(losses), round((length(losses)/nrow(df))*100, digits = 2), "%"))
   pwins <- round(sum(wins)/length(wins), digits = 2)
   plosses <- round(sum(losses)/length(losses), digits = 2)
   print(paste("Promedio Wins:", pwins, "EUR", "Promedio Losses:", plosses, "EUR"))
   exitopct <- round((length(wins) / nrow(df)) * 100, digits = 2)
   print(paste("Porcentaje de éxito:", exitopct, "%"))
   payout <- round(mean(wins) / abs(mean(losses)), digits = 2)
   print(paste("Payout ratio (W/L):", payout))
   print(paste("Profit factor:", round(sum(wins) / abs(sum(losses)), digits = 2)))
   print(paste("Net Profit", round((df$Saldo[nrow(df)] - (df$Saldo[1] - df$WLEUR[1])), digits = 2), "EUR"))
   print(paste("Retorno %:", round((((df$Saldo[nrow(df)] - (df$Saldo[1] - df$WLEUR[1]))) / (df$Saldo[1] - df$WLEUR[1])) * 100, digits = 2)))
   # esperanza
   x <- round((df$Saldo[nrow(df)] - (df$Saldo[1] - df$WLEUR[1])) / nrow(df), digits = 2)
   print(paste("Esperanza de ganancia: ", x, "EUR"))
   grp <- agrupar(df)
   # esperanza de ganancia positiva (múltiplo de R)
   espwin <- (grp$G3$pG3[[1]] * 3) + (grp$G2$pG2[[1]] * 2) + (grp$G1$pG1[[1]] * 1) + (grp$G0$pG0[[1]] * 0)
   print(paste("Esperanza de ganancia positiva:", espwin))
   # esperanza de ganacia negativa (múltiplo de R)
   esploss <- (grp$P3$pP3[[1]] * 3) + (grp$P2$pP2[[1]] * 2) + (grp$P1$pP1[[1]] * 1) + (grp$P0$pP0[[1]] * 0)
   print(paste("Esperanza de ganancia negativa:", esploss))
   # esperanza de ganancia por EUR arriesgado
   print(paste("Esperanza de ganancia por EUR arriesgado:", round(espwin - esploss, digits = 2)))
   # agrupar las ganancias y perdidas
   print("Agrupación de Ganáncias y Pérdidas en intervalos de 1EUR y Probabilidad")
   print(agrupar(df))
   # PINTAR GRÁFICOS
   fini <- format(df$FechaEntrada[1], format = paste("%Y-%m-%d"))
   ffin <- format(df$FechaSalida[nrow(df)], format = "%Y-%m-%d")
   print(paste("Fecha desde", df$FechaEntrada[1], "hasta", df$FechaSalida[nrow(df)]))
   frameplot <- par(mfrow = c(3, 2), oma = c(0, 0, 2, 0))
   # hist normal distribution w&l
   x <- cumsum(df$WLEUR)
   lim <- range(x)
   barplot(x, ylim = lim, xlab = "Operaciones", ylab = "Euros", main = paste("Acumulación de Ganancias y Pérdidas\n"))
   # plot saldo evolution
   plot(df$Saldo, type = "l", xlab = "Operaciones", ylab = "Saldo", main = paste("Evolución del Saldo\n"))
   abline(h = df$Saldo[1]) # para los colores usar ggplot
   grid()
   # plot normal distribution w&l
   #pintar(df$WLEUR) # http://www.statmethods.net/advgraphs/probability.html
   x <- sort(df$WLEUR)
   hx <- dnorm(x, mean = mean(df$WLEUR), sd = sd(df$WLEUR))
   plot(x, hx, type = "l", xlab = paste("Euros, desde ", range(x)[1], " hasta ", range(x)[2]), ylab = "Density", main = paste("Distribución Ganáncias y Pérdidas\n"))
   # pintar lineas verticales de media y mediana
   abline(v = mean(x))
   abline(v = median(x), lty = 2)
   # hist R
   barplot(df$brratio, xlab = "Operaciones", ylab = "R", main = paste("Distribución de R\n"))
   timeOp <- as.numeric(df$TimeOp)
   plot(timeOp, main = "The time difference in mins for operations", xlab = "", ylab = "Time differences", cex.lab = 0.8, cex.main = 0.8)
   abline(h = median(df$TimeOp), lty = 2)
   grid()
   hist(timeOp, main = "The time difference in mins for operations", xlab = "Time difference (mins)", ylab = "Observations", breaks = 10, cex.lab = 0.8, cex.main = 0.8)
   # cerrar el marco principal del gráfico
   mtext(paste("Estadísticas desde", fini, "hasta", ffin), outer = TRUE, cex = 1.5)
   par(frameplot)
   par(mfrow = c(1, 1))
}
