#' Write operations into csv file from data frame generated by readCMCreport.R
#'
#' \code{writeCMCreportToCsv} returns a csv file with one operation per row.
#'
#' @author Mario Pisa
#' @param data.frame generated by readCMCreport.R
#' @return csv file
#' @examples
#' writeCMCreportToCsv(operations)
#' @seealso \url{https://www.cmcmarkets.com/}
# cargar el resultado de leerOperaciones en un excel
#' @export
writeCMCreportToCsv <- function(df) {
   df <- df[order(df$FechaEntrada, decreasing = TRUE), ]
   xlsx::write.xlsx(df, file = "../CMC Markets/operacionesR.xlsx", sheetName = "operaciones", row.names = FALSE)
   print("Excel writed: ../CMC Markets/operacionesR.xlsx")
}
